document.addEventListener("DOMContentLoaded", () =>{
    const search = document.getElementById("search-music")
    const songName = document.getElementById("songname")
    const artist = document.getElementById("artist")
    const mute = document.getElementById("mute")
    const unmute = document.getElementById("unmute")
    const volumeDecrease = document.getElementById("volume-decrease")
    const volumeIncrease = document.getElementById("volume-increase")
    const repeat = document.getElementById("repeat")
    const play = document.getElementById("play")
    const like = document.getElementById("like")
    const newsletterInput = document.getElementById("newsletter-input")
    const submitNewsletter = document.getElementById("newsletter-btn")
    const a = document.getElementById("")
    const a = document.getElementById("")

} )