document.addEventListener("DOMContentLoaded", () =>{
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")
    const a = document.getElementById("")

} )